### ISSUE TITLE
Need more explanation about Reranking Dataset

### ISSUE THREAD

**Issue by Planck35** [dfcf93/MSMARCO#27]
In the [relevant passages](https://github.com/dfcf93/MSMARCO/blob/master/Ranking/README.md#relevant-passages), I am a bit confused about what the column value in each row means.

Such as 
```
1185869 0       0       1
1185868 0       16      1
597651  0       49      1
403613  0       60      1
1183785 0       389     1
312651  0       616     1
80385   0       723     1
645590  0       944     1
645337  0       1054    1
186154  0       1160    1
```
Given your explanation,  `Column 0 is queryID, column 2 is passageID`, as what will `column 1` and `column 3` mean, in this case?

Thanks

**Comment by dfcf93** [comment]
Column 1 and 3 are artifacts. please ignore. Ive updated the documentation to match
