### ISSUE TITLE
Different number of queries in collectionandqueries.tar.gz and top1000.dev.tar.gz

### ISSUE THREAD

**Issue by rodrigonogueira4** [dfcf93/MSMARCO#29]
There are different number of unique queries in dev set in collectionandqueries.tar.gz (101093) and top1000.dev.tar.gz (6980). 

Could you please update collectionandqueries.tar.gz with the smaller version? Otherwise, 101k queries take too long to evaluate. 

Same problem in the eval set.

**Comment by dfcf93** [comment]
Ive gone ahead an updated the collectionsandqueries.tar.gz to include queries and queries.*.small.tsv. Queries includes all queries in the split and queries.small includes only the ones referenced in the current public top1000.*.
