### ISSUE TITLE
Partially duplicated passages extracted

### ISSUE THREAD

**Issue by daltonj** [dfcf93/MSMARCO#33]
**Describe the bug**
This is a bug for the ranking passages collection. The bug is that some passages are partially duplicated.  The passage is partially replicated, but is also truncated incorrectly - leading to partial words being cut off.

**To Reproduce**
Below are three example passages. 

A search index is available at:
http://boston.lti.cs.cmu.edu/Services/treccast19

http://boston.lti.cs.cmu.edu/Services/treccast19/lemur.cgi?d=0&i=7564736
Average physician assistant salary. Physician assistant’s salary is ranging from $68,587 to $117,554 pay per year. The average physician assistant’s salary is $87,749. Generally, a new physician assistant earns an hourly pay ranging from $28.13 to 50.00.Read more about average PA salary in USA.verage physician assistant salary. Physician assistant’s salary is ranging from $68,587 to $117,554 pay per year. The average physician assistant’s salary is $87,749. Generally, a new physician assistant earns an hourly pay ranging from $28.13 to 50.00.

In the above the duplicate passage starts at ".verage physician assistant salary.." and continues. 

http://boston.lti.cs.cmu.edu/Services/treccast19/lemur.cgi?d=0&i=107258
This is a list of goat breeds. There are many recognized breeds of domestic goat (Capra aegagrus hircus) . Goat breeds (especially dairy goats) are some of the oldest defined animal breeds for which breed standards and production records have been kept.his is a list of goat breeds. There are many recognized breeds of domestic goat (Capra aegagrus hircus) . Goat breeds (especially dairy goats) are some of the oldest defined animal breeds for which breed standards and productio

In the above passage the duplicate portion starts at "There are many recognized breeds" and is truncated not on a word boundary.

http://boston.lti.cs.cmu.edu/Services/treccast19/lemur.cgi?d=0&i=15744716
Jamunapari Goat. Jamunapari goat is a very beautiful dairy goat breed which was originated from India. This breed first introduced near a river of Uttar Pradesh named Jamuna. Since this breed is mostly known as Jamunapari goat. They are also known as some other names like Jamnapari, Ram Sagol etc.They become highly meat and milk productive and also very suitable for show. In India this goat breed is considered as the best dairy goat.They are one of the giant goat breeds with a pair of very long ear. The physical characteristics, feeding, housing, breeding and caring of Jamunapari goat are described below.hey are also known as some other names like Jamnapari, Ram Sagol etc. They become highly meat and milk productive and also very suitable for show. In India this goat breed is considered as the best dairy goat. They are one of the giant goat breeds with a pair of very long ear.

The duplicate section starts at ".hey are also known as some other names like Jamnapari, Ram Sagol etc..." Again started not on a good word boundary.

**Additional context**

**Comment by daltonj** [comment]
FYI - It turns out the data is for the QA data, but the same issue exists in the ranking data as well.

**Comment by dfcf93** [comment]
Hey, 

The MSMARCO dataset was generated by leveraging the Question Answering capabilities of Bing. For each query, Bing retrieved the 10 most relevant context passages. These passages are generated independelty of any query. Passages are generated by scanning over full documents and extrating all possible passages. Only the top N passages are kept in an index. What this means is it is possible that context passages have high overlaps in their ngrams.

**Comment by daltonj** [comment]
Thanks for the explanation. I understand how it was created.  

In this case it appears there is a bug in the extraction.  What the above shows is that passages are cutting chunks of duplicates in the SAME context passage.  Each of the above is a single "passage document" which chunks of partially repeated text.  There also appears to be a bug because the passages were not being truncated correctly (e.g. word boundaries).

**Comment by dfcf93** [comment]
I dont think this is a bug. This is something that passage ranking systems have to deal with. Since its not really possible to generate passages on the fly due to latency reasons systems must learn to identify which of the passages with similair text is best suited to display. Until we have a scalable efficient way of generating the relevant context passages on the fly we will likley continue to generate all possible passages and select the best ones.
