### ISSUE TITLE
OpenKPAnnotations.tsv for Key Phrase Extraction

### ISSUE THREAD

**Issue by zeynepakkalyoncu** [dfcf93/MSMARCO#36]
Thanks for the great work!

Could you let me know how to access or generate the `OpenKPAnnotations.tsv` file used in the [notebook](https://github.com/dfcf93/MSMARCO/blob/master/KeyPhraseExtraction/JudgeQualityEvaluation.ipynb) for key phrase extraction please?

**Comment by dfcf93** [comment]
This is an upcoming project. Check beck in about a month and we should have public data.
