### ISSUE TITLE
Regarding the Test Set for Q&A

### ISSUE THREAD

**Issue by tahmedge** [dfcf93/MSMARCO#38]
Hi, 

In your website, you have, training, dev, and evaluation set for Q&A. I want to know, what is the difference between dev-set and evaluation-set? And where can I find the test-data to submit the result for the leaderboard?

**Comment by spacemanidol** [comment]
@tahmedge  eval is the test set. Eval is held out for blind evaluation

**Comment by tahmedge** [comment]
It is mentioned that we need to "Run the evaluation script on the test/dev set and generate the output results file for submission." Now, since the test data doesn't contain the answers, what would be the reference file to run the evaluation script? Also, how to submit the result only for the well-formed version?
